### ISSUE TITLE
Is there a text limit on the volume of diacritics?

### ISSUE THREAD

**Issue by Kentoseth** [mush42/libtashkeel#2]
السلام عليكم

Your library is being used downstream via these two:

https://github.com/rhasspy/piper-phonemize/blob/master/etc/libtashkeel_model.ort > https://github.com/mkiol/dsnote

Based on issue https://github.com/mkiol/dsnote/issues/92

I've been attempting to diacriticize a 450 char text, but the solution only partially diacriticizes. Here is the input:

> الإيمان في اللغة يُطلق على التصديق المحض كَمَا قَالَ تَعَالَى {يُؤْمِنُ بِاللَّهِ وَيُؤْمِنُ لِلْمُؤْمِنِينَ}، وَكَمَا قَالَ إِخْوَةُ يُوسُفَ لِأَبِيهِمْ: {وَمَآ أَنتَ بِمُؤْمِنٍ لَّنَا وَلَوْ كُنَّا صَادِقِينَ} وكذلك إذا استعمل مقروناً مع الأعمال: {إِلَاّ الذين آمَنُواْ وعملوا الصالحات} فأما إذا استعمل مطلقاً فالإيمان المطلوب لا يكون إلا اعتقاداً وقولاً عملاً، هكذا ذهب أكثر الأئمة وحكاه الشافعي وأحمد إِجْمَاعًا: أَنَّ الْإِيمَانَ قَوْلٌ وَعَمَلٌ، يَزِيدُ وَيَنْقُصُ وقد ورد فيه آثار كثيرة أفردنا الْكَلَامَ فِيهَا فِي أَوَّلِ شَرْحِ الْبُخَارِيِّ وَلِلَّهِ الْحَمْدُ وَالْمِنَّةُ، ومنهم من فسره بالخشية: {إِنَّ الذين يَخْشَوْنَ ربهم بالغيب} والخشيةُ خلاصة الإيمان العلم: {إِنَّمَا يَخْشَى اللهَ مِنْ عِبَادِهِ العلماء}.

Output:

> الْإِيمَانُ فِي اللُّغَةِ يُطْلَقُ عَلَى التَّصْدِيقِ الْمَحْضِ كَمَا قَالَ تَعَالَى {يُؤْمِنُ بِاَللَّهِ وَيُؤْمِنُ لِلْمُؤْمِنِينَ}، وَكَمَا قَالَ إخْوَةُ يُوسُفُ لِأَبِيهِمَ: {وَمَآ أَنْتَ بِمُؤْمِنٍ لَنَا وَلَوْ كُنَّا صَادِقِينِ} وَكَذَلِكَ إذَا اسْتُعْمَلَ مَقْرُونًاً مَعَ الْأَعْمَالِ: {إلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ} فَأَمَّا إذَا اسْتُعْمَلَ مُطْلَقًاً فَالْإِيمَانُ الْمَطْلُوبُ لَا يَكُونُ إلَّا اعْتِقَادًاً وَقَوْلًاً عَمَلًاً، هَكَذَا ذَهَبَ أَكْثَرُ الْأَئِمَّةِ وَحَكْاه الشافعي وأحمد إجماعًا: أن الإيمان قول وعمل، يزيد وينقص وقد ورد فيه آثار كثيرة أفردنا الكلام فيها في أول شرح البخاري ولله الحمد والمنة، ومنهم من فسره بالخشية: {إن الذين يخشون ربهم بالغيب} والخشية خلاصة الإيمان العلم: {إنما يخشى الله من عباده العلماء}.

The limitation seems to be around 300 chars.

**Comment by mush42** [comment]
Hi,

The model used in `piper-phonemize` is the **MVP** of this project (migrated from Python. It uses [Shakkala](https://github.com/Barqawiz/Shakkala) which has a character limit of **300** chars.

I recommend migrating to the implementation in this repo, which uses a different model architecture. It supports unlimited characters, splits text into sentences before diacritization, diacritizes sentences in parallel, takes into acount the existing diacritics, and is actively maintained.

I can help with any integration work if needed.

Best
Musharraf

**Comment by mush42** [comment]
`libtashkeel` has `C` and `Python` bindings, integration is not that hard since it provides a single function `do_tashkeel` that takes some Arabic text and some options and returns the diacritized text.

**Comment by Kentoseth** [comment]
> I recommend migrating to the implementation in this repo, which uses a different model architecture. It supports unlimited characters, splits text into sentences before diacritization, diacritizes sentences in parallel, takes into acount the existing diacritics, and is actively maintained.

 1. Which model is your current one in the repo? Is it Shakkelha?
 2. How does the model account for existing diacritics? I encountered this issue with Shakkelha and the solution I suggested to the owner may not have been accurate (preserving existing diacritics and putting diacritics on unvowelled letters) - https://github.com/AliOsm/shakkelha-website/issues/2

Can you tell me where the .ort file is that should be in this repository? I do not seem to see it. I only see a .onnx file.

Here are screenshots of how the .ort file is downloaded into the application mentioned above:

![spn1](https://github.com/mush42/libtashkeel/assets/2989402/ca8afbc0-4c73-4fb9-b646-e28902672ebc)

![spn2](https://github.com/mush42/libtashkeel/assets/2989402/3f4b22ba-521b-4b76-9b4e-525c1063bcc3)

**Comment by mush42** [comment]
> 1. Which model is your current one in the repo? Is it Shakkelha?

I'm using a custom model architecture, designed for efficiency and quality, called **sarf**.
I intend to publish it under the sarf model in [this repo](https://github.com/mush42/hareef)

> 2. How does the model account for existing diacritics?

The model is trained to handle existing diacritics. During training, the model is exposed to different sentences some of which contain diacritical hints. This way it learns which diacritics to copy as is, which ones to change, and which ones to discard.
This feature is loosely modeled after the approach used in [this paper](https://arxiv.org/pdf/2306.03557.pdf)

> Can you tell me where the .ort file is that should be in this repository?

Unfortunately, you cannot just copy the `.ort` file and expect it to work. The model in this repo expects inputs in certain format which is totally different from the input format of `Shakkala`.
The only way to use the model from this repo is to build the component you need from this repo (e.g. python bindings, command line app..etc.), this requires installing Rust. Refer to the `readme` for how to build the repo.

In the mean time, you can try an [online demo of this model](https://mush42.github.io/libtashkeel/), which runs entirely on your browser via `WebAssembly`.

Best
Musharraf
