### ISSUE TITLE
Unable to build libtashkeel

### ISSUE THREAD

**Issue by Andrey847** [mush42/libtashkeel#6]
New ubuntu machine 22.04

cloned repo, installed rust, tried to build libtashkeel by "cargo build --release", got this error. What could be the reason?

 Compiling libtashkeel_base v1.5.0 (/root/libtashkeel/libtashkeel_base)
error[E0277]: the trait bound `ort::Value: From<ArrayBase<OwnedRepr<i64>, Dim<[usize; 2]>>>` is not satisfied
  --> libtashkeel_base/src/inference_engine/ort.rs:26:22
   |
26 |           let inputs = ort::inputs![
   |  ______________________^
27 | |             input_ids,
28 | |             diac_ids,
29 | |             input_length,
30 | |         ]?;
   | |_________^ the trait `From<ArrayBase<OwnedRepr<i64>, Dim<[usize; 2]>>>` is not implemented for `ort::Value`, which is required by `ort::Value: TryFrom<ArrayBase<OwnedRepr<i64>, Dim<[usize; 2]>>>`
   |
   = help: the following other types implement trait `From<T>`:
             `ort::Value` implements `From<ort::Value<DynTensorValueType>>`
             `ort::Value` implements `From<ort::Value<TensorValueType<T>>>`
   = note: required for `ArrayBase<OwnedRepr<i64>, Dim<[usize; 2]>>` to implement `Into<ort::Value>`
   = note: required for `ort::Value` to implement `TryFrom<ArrayBase<OwnedRepr<i64>, Dim<[usize; 2]>>>`
   = note: this error originates in the macro `ort::inputs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `ort::Value: From<ArrayBase<OwnedRepr<i64>, Dim<[usize; 1]>>>` is not satisfied
  --> libtashkeel_base/src/inference_engine/ort.rs:26:22
   |
26 |           let inputs = ort::inputs![
   |  ______________________^
27 | |             input_ids,
28 | |             diac_ids,
29 | |             input_length,
30 | |         ]?;
   | |_________^ the trait `From<ArrayBase<OwnedRepr<i64>, Dim<[usize; 1]>>>` is not implemented for `ort::Value`, which is required by `ort::Value: TryFrom<ArrayBase<OwnedRepr<i64>, Dim<[usize; 1]>>>`
   |
   = help: the following other types implement trait `From<T>`:
             `ort::Value` implements `From<ort::Value<DynTensorValueType>>`
             `ort::Value` implements `From<ort::Value<TensorValueType<T>>>`
   = note: required for `ArrayBase<OwnedRepr<i64>, Dim<[usize; 1]>>` to implement `Into<ort::Value>`
   = note: required for `ort::Value` to implement `TryFrom<ArrayBase<OwnedRepr<i64>, Dim<[usize; 1]>>>`
   = note: this error originates in the macro `ort::inputs` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `libtashkeel_base` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by mush42** [comment]
@Andrey847 thanks for reporting this. Please try building with the latest commit.

**Comment by Andrey847** [comment]
Thanks! this commit helped.

After the updating the source, I' ve got this error:

  = note: /usr/bin/ld: cannot find -lstdc++: No such file or directory

Which was fixed by these commands:

- sudo apt-get update
- sudo apt-get install build-essential
- sudo apt-get install aptitude
- sudo apt-get install libstdc++6

**Comment by mush42** [comment]
@Andrey847 thanks. I'm sure this would be a good reference for others.
